Compile against the latest Android Gradle plugin
It seems that the signature of the AppExtension[1] class changed,
causing a java.lang.NoSuchMethodError when included in projects
configured with newer versions of the Gradle plugin. See [2] for similar
discussion.

[1] com.android.build.gradle.AppExtension.getApplicationVariants
[2] https://github.com/xtext/xtend-gradle-plugin/issues/34